// cypress/support/githubDefects.js
const { Octokit } = require('@octokit/rest');

class GitHubDefectReporter {
  constructor() {
    this.octokit = new Octokit({
      auth: process.env.GITHUB_TOKEN
    });
    this.owner = process.env.GITHUB_OWNER || 'your-username';
    this.repo = process.env.GITHUB_REPO || 'hackathon-automation';
  }

  async createIssue(testFailure) {
    const issueData = {
      owner: this.owner,
      repo: this.repo,
      title: `🐛 Login Test Failure: ${testFailure.testName}`,
      body: this.formatIssueBody(testFailure),
      labels: ['bug', 'automation', 'login', this.getPriorityLabel(testFailure.tags)],
      assignees: [process.env.GITHUB_ASSIGNEE || 'qa-team']
    };

    try {
      const response = await this.octokit.rest.issues.create(issueData);
      console.log(`✅ GitHub issue created: #${response.data.number}`);
      
      // Add screenshot comment if available
      if (testFailure.screenshots.length > 0) {
        await this.addScreenshotComment(response.data.number, testFailure.screenshots);
      }
      
      return response.data.number;
    } catch (error) {
      console.error('❌ Failed to create GitHub issue:', error.message);
    }
  }

  formatIssueBody(failure) {
    return `
## 🚨 Test Failure Report

### 📋 Test Information
- **Test Name:** ${failure.testName}
- **Feature:** ${failure.specFile}
- **Browser:** ${failure.browser}
- **Environment:** ${failure.environment}
- **Timestamp:** ${new Date().toISOString()}

### 💥 Failure Details
\`\`\`
${failure.errorMessage}
\`\`\`

### 📚 Stack Trace
\`\`\`javascript
${failure.stackTrace}
\`\`\`

### 🎯 Test Scenario
\`\`\`gherkin
${failure.scenario}
\`\`\`

### 🔄 Reproduction Steps
1. Navigate to: \`${failure.pageUrl}\`
2. Execute test: "${failure.testName}"
3. Failed at step: "${failure.failedStep}"

### 🖥️ Environment
- **OS:** ${failure.os}
- **Cypress:** ${failure.cypressVersion}
- **Node:** ${failure.nodeVersion}
- **Viewport:** ${failure.viewport}

### 📊 Expected vs Actual
- **Expected:** ${failure.expected}
- **Actual:** ${failure.actual}

### 🏷️ Tags
${failure.tags.map(tag => `\`${tag}\``).join(' ')}

---
*Auto-generated by DevX Hackathon Automation Framework*
`;
  }

  getPriorityLabel(tags) {
    if (tags.includes('@critical')) return 'priority: high';
    if (tags.includes('@high')) return 'priority: medium';
    return 'priority: low';
  }

  async addScreenshotComment(issueNumber, screenshots) {
    const comment = `
## 📸 Failure Screenshots

${screenshots.map((img, index) => `
### Screenshot ${index + 1}
![Failure Screenshot ${index + 1}](${img})
`).join('\n')}
`;

    await this.octokit.rest.issues.createComment({
      owner: this.owner,
      repo: this.repo,
      issue_number: issueNumber,
      body: comment
    });
  }
}

module.exports = GitHubDefectReporter;