// cypress/support/localTicketLogger.js
const fs = require('fs');
const path = require('path');

class LocalTicketLogger {
  constructor() {
    this.ticketsDir = path.join(process.cwd(), 'generated-tickets');
    this.ensureTicketsDirectory();
  }

  ensureTicketsDirectory() {
    if (!fs.existsSync(this.ticketsDir)) {
      fs.mkdirSync(this.ticketsDir, { recursive: true });
    }
  }

  async createDefectTicket(testFailure) {
    const ticketId = `DEFECT-${Date.now()}`;
    const ticket = {
      ticketId: ticketId,
      type: 'Bug',
      priority: this.getPriority(testFailure.tags),
      created: new Date().toISOString(),
      summary: `🐛 Test Failure: ${testFailure.testName}`,
      description: this.formatDefectDescription(testFailure),
      project: 'SCRUM',
      board: 'Board 1',
      status: 'To Do',
      assignee: 'prasant.lohiya@sierradev.com',
      labels: ['automation', 'cypress', 'login-test'],
      environment: testFailure.environment,
      browser: testFailure.browser,
      screenshots: testFailure.screenshots || [],
      videoUrl: testFailure.videoUrl
    };

    const fileName = `${ticketId}_defect_ticket.json`;
    fs.writeFileSync(
      path.join(this.ticketsDir, fileName), 
      JSON.stringify(ticket, null, 2)
    );

    // Also create human-readable version
    const readableFileName = `${ticketId}_defect_ticket.md`;
    fs.writeFileSync(
      path.join(this.ticketsDir, readableFileName), 
      this.formatDefectMarkdown(ticket)
    );

    console.log(`🎫 LOCAL DEFECT TICKET CREATED: ${ticketId}`);
    console.log(`📁 Saved to: generated-tickets/${fileName}`);
    console.log(`📄 Readable version: generated-tickets/${readableFileName}`);
    
    return ticketId;
  }

  async createSuccessTicket(testSuccess) {
    const ticketId = `SUCCESS-${Date.now()}`;
    const ticket = {
      ticketId: ticketId,
      type: 'Task',
      priority: 'Medium',
      created: new Date().toISOString(),
      summary: `✅ Test Suite Passed: ${testSuccess.suiteName}`,
      description: this.formatSuccessDescription(testSuccess),
      project: 'SCRUM',
      board: 'Board 1',
      status: 'Done',
      assignee: 'prasant.lohiya@sierradev.com',
      labels: ['automation', 'cypress', 'test-success', 'login-test'],
      environment: testSuccess.environment,
      browser: testSuccess.browser,
      totalTests: testSuccess.totalTests,
      passedTests: testSuccess.passedTests,
      duration: testSuccess.duration,
      successRate: '100%',
      videoUrl: testSuccess.videoUrl
    };

    const fileName = `${ticketId}_success_ticket.json`;
    fs.writeFileSync(
      path.join(this.ticketsDir, fileName), 
      JSON.stringify(ticket, null, 2)
    );

    // Also create human-readable version
    const readableFileName = `${ticketId}_success_ticket.md`;
    fs.writeFileSync(
      path.join(this.ticketsDir, readableFileName), 
      this.formatSuccessMarkdown(ticket)
    );

    console.log(`🎉 LOCAL SUCCESS TICKET CREATED: ${ticketId}`);
    console.log(`📁 Saved to: generated-tickets/${fileName}`);
    console.log(`📄 Readable version: generated-tickets/${readableFileName}`);
    
    return ticketId;
  }

  formatDefectDescription(failure) {
    return `**Test Failure Report - DevX Hackathon Automation**

## Test Details
- **Test Name:** ${failure.testName}
- **Feature File:** ${failure.specFile}
- **Browser:** ${failure.browser}
- **Environment:** ${failure.environment}
- **Execution Time:** ${new Date().toISOString()}

## Failure Information
- **Error Message:** ${failure.errorMessage}
- **Stack Trace:**
\`\`\`
${failure.stackTrace}
\`\`\`

## Environment Information
- **OS:** ${failure.os}
- **Cypress Version:** ${failure.cypressVersion}
- **Node Version:** ${failure.nodeVersion}
- **Viewport:** ${failure.viewport}

## Reproduction Steps
1. Navigate to ${failure.pageUrl}
2. Execute test scenario: "${failure.scenario}"
3. Observe failure at step: "${failure.failedStep}"

## Expected vs Actual
- **Expected:** ${failure.expected}
- **Actual:** ${failure.actual}

*Auto-generated by Cypress Test Automation Framework*`;
  }

  formatSuccessDescription(success) {
    return `**Comprehensive Test Success Report - DevX Hackathon Automation**

## Executive Summary
- **Test Suite:** ${success.suiteName}
- **Total Tests:** ${success.totalTests}
- **Success Rate:** 100% ✅
- **Duration:** ${success.duration}ms
- **Browser:** ${success.browser}
- **Environment:** ${success.environment}

## Test Results
${success.passedScenarios.map((scenario, index) => `
### Test ${index + 1}: ${scenario}
- **Status:** ✅ PASSED
- **Category:** ${this.categorizeTest(scenario)}
- **Priority:** ${this.getTestPriority(scenario)}
`).join('')}

## Quality Gates
- ✅ All authentication scenarios passed
- ✅ Form validation working correctly
- ✅ Responsive design verified
- ✅ Accessibility checks passed

## Release Readiness
- ✅ Ready for deployment
- ✅ All quality requirements met
- ✅ 100% test coverage achieved

*Auto-generated by Cypress Test Automation Framework*`;
  }

  formatDefectMarkdown(ticket) {
    return `# 🐛 Defect Ticket: ${ticket.ticketId}

**Created:** ${ticket.created}
**Type:** ${ticket.type}
**Priority:** ${ticket.priority}
**Status:** ${ticket.status}
**Project:** ${ticket.project}
**Board:** ${ticket.board}

## Summary
${ticket.summary}

## Description
${ticket.description}

## Technical Details
- **Browser:** ${ticket.browser}
- **Environment:** ${ticket.environment}
- **Screenshots:** ${ticket.screenshots.length} captured
- **Video:** ${ticket.videoUrl}

---
*This ticket would be created in Jira with proper permissions*`;
  }

  formatSuccessMarkdown(ticket) {
    return `# ✅ Success Ticket: ${ticket.ticketId}

**Created:** ${ticket.created}
**Type:** ${ticket.type}
**Priority:** ${ticket.priority}
**Status:** ${ticket.status}
**Project:** ${ticket.project}
**Board:** ${ticket.board}

## Summary
${ticket.summary}

## Results
- **Total Tests:** ${ticket.totalTests}
- **Passed Tests:** ${ticket.passedTests}
- **Success Rate:** ${ticket.successRate}
- **Duration:** ${ticket.duration}ms

## Description
${ticket.description}

## Quality Confirmation
- **Browser:** ${ticket.browser}
- **Environment:** ${ticket.environment}
- **Video Recording:** ${ticket.videoUrl}

---
*This ticket would be created in Jira with proper permissions*`;
  }

  getPriority(tags) {
    if (tags && tags.includes('@critical')) return 'High';
    if (tags && tags.includes('@high')) return 'Medium';
    return 'Low';
  }

  categorizeTest(testTitle) {
    const title = testTitle.toLowerCase();
    if (title.includes('login') || title.includes('authentication')) return 'Authentication';
    if (title.includes('validation') || title.includes('error')) return 'Validation';
    if (title.includes('responsive') || title.includes('mobile')) return 'Responsive Design';
    if (title.includes('accessible') || title.includes('a11y')) return 'Accessibility';
    if (title.includes('password') || title.includes('security')) return 'Security';
    return 'Functional';
  }

  getTestPriority(testTitle) {
    const title = testTitle.toLowerCase();
    if (title.includes('login') || title.includes('security') || title.includes('accessible')) return 'Critical';
    if (title.includes('validation') || title.includes('error')) return 'High';
    return 'Medium';
  }
}

module.exports = LocalTicketLogger;