const report = require('multiple-cucumber-html-reporter');
const fs = require('fs');
const path = require('path');

// Create reports directory if it doesn't exist
const reportsDir = path.join(__dirname, '../cypress/reports');
const htmlReportsDir = path.join(reportsDir, 'cucumber-html-reports');

if (!fs.existsSync(htmlReportsDir)) {
  fs.mkdirSync(htmlReportsDir, { recursive: true });
}

// Generate the beautiful HTML report
report.generate({
  jsonDir: reportsDir,
  reportPath: htmlReportsDir,
  openReportInBrowser: false,
  displayDuration: true,
  displayReportTime: true,
  useCDN: true,
  pageTitle: '🚀 Login Automation Test Report',
  reportName: 'Login Page BDD Test Results',
  pageFooter: '<div style="text-align:center;"><p>Generated by Cypress BDD Framework</p></div>',
  customStyle: `
    .navbar-brand {
      color: #28a745 !important;
      font-weight: bold;
    }
    .feature-overview {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      border-radius: 10px;
      padding: 20px;
      margin: 20px 0;
    }
    .scenario-container {
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
      margin: 15px 0;
    }
    .passed {
      border-left: 5px solid #28a745;
    }
    .failed {
      border-left: 5px solid #dc3545;
    }
    .tag {
      background: #007bff;
      color: white;
      border-radius: 12px;
      padding: 3px 8px;
      font-size: 0.8em;
      margin: 2px;
    }
  `,
  metadata: {
    browser: {
      name: 'Electron',
      version: '118'
    },
    device: 'Local Test Machine',
    platform: {
      name: 'Windows',
      version: '11'
    }
  },
  customData: {
    title: 'Login Page Automation Test Results',
    data: [
      { label: 'Project', value: 'Hackathon Automation Framework' },
      { label: 'Version', value: '1.0.0' },
      { label: 'Test Environment', value: 'http://localhost:5173/login' },
      { label: 'Framework', value: 'Cypress + BDD (Cucumber)' },
      { label: 'Execution Date', value: new Date().toISOString().split('T')[0] },
      { label: 'Execution Time', value: new Date().toTimeString().split(' ')[0] }
    ]
  }
});

console.log('✅ Beautiful HTML reports generated successfully!');
console.log('📁 Location: cypress/reports/cucumber-html-reports/');
console.log('🌐 Open index.html in your browser to view the report');